version: "3.8"
services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_network:
        aliases:
          - postgres
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # API .NET
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}:production
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      app_network:
        aliases:
          - api
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  # Nginx como gateway único
  nginx:
    image: nginx:1.25.5-alpine
    ports:
      - "80:80"
    networks:
      - app_network
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 128M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "nginx -t && curl -f http://localhost/nginx-health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Métricas del sistema host (Node Exporter)
  node-exporter:
    image: prom/node-exporter:v1.8.2
    command:
      - "--path.rootfs=/host"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave
    networks:
      - app_network
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Métricas de contenedores (cAdvisor)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - app_network
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Prometheus para recolección de métricas
  prometheus:
    image: prom/prometheus:v2.54.1
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=200h"
      - "--web.external-url=/prometheus/"
      - "--web.route-prefix=/prometheus/"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
    networks:
      app_network:
        aliases:
          - prometheus
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # Grafana para visualización de dashboards
  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      app_network:
        aliases:
          - grafana
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  postgres_data: {}
  prometheus_data: {}
  grafana_data: {}

networks:
  app_network:
    driver: overlay
    attachable: true

configs:
  nginx_config:
    file: ./nginx.conf
  prometheus_config:
    file: ./prometheus.yml
