global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus se monitorea a sí mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter - métricas del sistema host
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor - métricas de contenedores Docker
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    metrics_path: /metrics

  # API aplicación - si expone métricas
  - job_name: "api-health"
    static_configs:
      - targets: ["api:8080"]
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 10s

  # Nginx - si se configura métricas (opcional)
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    scrape_interval: 30s
    metrics_path: /nginx-health
    scrape_timeout: 10s
