name: Docker Registry DEV
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Log in to Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3.12.0
        with:
          server_address: ${{ secrets.DEBUGMAIL_HOST }}
          server_port: ${{ secrets.DEBUGMAIL_PORT }}
          username: ${{ secrets.DEBUGMAIL_USER }}
          password: ${{ secrets.DEBUGMAIL_PASS }}
          subject: "Docker Registry Build ${{ job.status }} - ${{ github.repository }}"
          body: |
            El pipeline de Docker Registry ha finalizado.

            Repositorio: ${{ github.repository }}
            Rama: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Estado: ${{ job.status }}

            Imagen creada: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            Ver detalles: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.DEBUGMAIL_USER }}
